<?php

return [
    ['name' => 'Black', 'hex' => '000000',],
    ['name' => 'Negro Black', 'hex' => '222a2e',],
    ['name' => 'Black Grey', 'hex' => '485057',],
    ['name' => 'Neutral Grey', 'hex' => '666f79',],
    ['name' => 'Stonewall Grey', 'hex' => '979a9f',],
    ['name' => 'Ghost Grey', 'hex' => 'b3c2cd',],
    ['name' => 'White', 'hex' => 'ffffff',],
    ['name' => 'Orange Fire', 'hex' => 'f06a27',],
    ['name' => 'Bronze Fleshtone', 'hex' => 'c0824f',],
    ['name' => 'Beast Brown', 'hex' => '6f5441',],
    ['name' => 'Scab Red', 'hex' => '6a0002',],
    ['name' => 'Vermillion', 'hex' => 'd3292b',],
    ['name' => 'Bloody Red', 'hex' => 'bf223d',],
    ['name' => 'Hexed Lichen', 'hex' => '55368d',],
    ['name' => 'Squid Pink', 'hex' => 'cb84b9',],
    ['name' => 'Basic Skintone', 'hex' => 'f0b298',],
    ['name' => 'Ultramarine Blue', 'hex' => '2a5c92',],
    ['name' => 'Deep Sky Blue', 'hex' => '2db0df',],
    ['name' => 'Turquoise', 'hex' => '018694',],
    ['name' => 'Dark Green', 'hex' => '33423d',],
    ['name' => 'Goblin Green', 'hex' => '646f49',],
    ['name' => 'Gold Yellow', 'hex' => 'f69120',],
    ['name' => 'Sun Yellow', 'hex' => 'f89c1c',],
    ['name' => 'Khaki Grey', 'hex' => '7c7560',],
    ['name' => 'Bonewhite', 'hex' => 'cbb893',],
    ['name' => 'Offwhite', 'hex' => 'fbefd3',],
    ['name' => 'Leather Brown', 'hex' => '7e6140',],
];
