<?php

return [
    ['name' => 'Black', 'hex' => '030708',],
    ['name' => 'Negro Black', 'hex' => '080e0e',],
    ['name' => 'Black Grey', 'hex' => '474b4e',],
    ['name' => 'Neutral Grey', 'hex' => '666a73',],
    ['name' => 'Stonewall Grey', 'hex' => '869193',],
    ['name' => 'Ghost Grey', 'hex' => 'b9cee3',],
    ['name' => 'White', 'hex' => 'fdfdfd',],
    ['name' => 'Orange Fire', 'hex' => 'e6742e',],
    ['name' => 'Bronze Fleshtone', 'hex' => 'e79c5a',],
    ['name' => 'Beast Brown', 'hex' => '675139',],
    ['name' => 'Scab Red', 'hex' => '8f253c',],
    ['name' => 'Vermillion', 'hex' => 'e41f2b',],
    ['name' => 'Bloody Red', 'hex' => 'c41821',],
    ['name' => 'Hexed Lichen', 'hex' => '352a4c',],
    ['name' => 'Squid Pink', 'hex' => 'd881ae',],
    ['name' => 'Basic Skintone', 'hex' => 'ecb399',],
    ['name' => 'Ultramarine Blue', 'hex' => '2a5c92',],
    ['name' => 'Deep Sky Blue', 'hex' => '47bae7',],
    ['name' => 'Turquoise', 'hex' => '387c8e',],
    ['name' => 'Dark Green', 'hex' => '072f26',],
    ['name' => 'Goblin Green', 'hex' => '14692a',],
    ['name' => 'Gold Yellow', 'hex' => 'fbad01',],
    ['name' => 'Sun Yellow', 'hex' => 'fccd05',],
    ['name' => 'Khaki Grey', 'hex' => '88785c',],
    ['name' => 'Bonewhite', 'hex' => 'f1c685',],
    ['name' => 'Offwhite', 'hex' => 'e2e2d7',],
    ['name' => 'Leather Brown', 'hex' => '72511c',],
    ['name' => 'Ochre Brown', 'hex' => 'b47827',],
    ['name' => 'Lemon Yellow', 'hex' => 'f5e708',],
    ['name' => 'Intermediate Green', 'hex' => '519947',],
    ['name' => 'Medium Grey', 'hex' => '9ba180',],
    ['name' => 'Hull Red', 'hex' => '5c322e',],
    ['name' => 'Blue Violet', 'hex' => '7066a3',],
    ['name' => 'Golden Olive', 'hex' => '7a7943',],
    ['name' => 'Dark Sand', 'hex' => 'd4b685',],
    ['name' => 'Brown Violet', 'hex' => '5d5747',],
    ['name' => 'Flat Earth', 'hex' => '7d6246',],
    ['name' => 'Olive Green', 'hex' => '4d594f',],
    ['name' => 'Mephiston Red', 'hex' => '991115'],
    ['name' => 'Tallarn Flesh', 'hex' => '9f8088'],
    
    // wishlist

    // idea
    ['name' => 'Orange Brown', 'hex' => 'cb7b43', 'label' => 'Coming'],
    ['name' => 'Dark Yellow', 'hex' => '91834c', 'label' => 'Coming'],
    ['name' => 'Sunny Skintone', 'hex' => 'e9aa74', 'label' => 'Coming'],
    ['name' => 'Filthy Brown', 'hex' => 'f18e11', 'label' => 'Coming'],
    ['name' => 'Japanese Uniform', 'hex' => '9d7b3c', 'label' => 'Idea'],
    ['name' => 'Scrofulous Brown', 'hex' => 'd47e1c', 'label' => 'Idea'],
    ['name' => 'Brown Sand', 'hex' => '9d755c', 'label' => 'Idea'],
    ['name' => 'Light Sea Grey', 'hex' => 'a5b7b7', 'label' => 'Idea'],
    // ['name' => 'Middlestone', 'hex' => '9e8857', 'label' => 'Idea'],
    // ['name' => 'Emerald', 'hex' => '08976b', 'label' => 'Idea'],
    // ['name' => 'Light Green Blue', 'hex' => '7ca59d', 'label' => 'Idea'],
    // ['name' => 'Violet Red', 'hex' => '732a42', 'label' => 'Idea'],
    // ['name' => 'Black Green', 'hex' => '46514b', 'label' => 'Idea'],
    // ['name' => 'Beige Brown', 'hex' => '90765e', 'label' => 'Idea'],
    // ['name' => 'Light Flesh', 'hex' => 'dabfae', 'label' => 'Idea'],
    // ['name' => 'Royal Purple', 'hex' => '574362', 'label' => 'Idea'],
    // ['name' => 'Purple', 'hex' => '80455f', 'label' => 'Idea'],
    // ['name' => 'Lime Green', 'hex' => '919642', 'label' => 'Idea'],
    // ['name' => 'Oxford Blue', 'hex' => '525271', 'label' => 'Idea'],
    // ['name' => 'Clear Orange', 'hex' => 'e45c48', 'label' => 'Idea'],
    // ['name' => 'Stone Grey', 'hex' => 'a9a985', 'label' => 'Idea'],
    // ['name' => 'Deck Tan', 'hex' => 'cbd0ba', 'label' => 'Idea'],
];
